### ISSUE TITLE
Possible to create an altcoin using haskcoin?

### ISSUE THREAD

**Issue by purefn** [jprupp/haskoin-core#144]
Hey folks,

I asked this question in IRC some time ago and didn't get an answer. I'm still interested in figuring this out, in particular I'd like to mess with the mining hash function in addition to all the normal parameters. Would I be able to do that with haskoin? If so, could someone write up a brief howto?

**Comment by jprupp** [comment]
Mello purefn,

Currently we haven't the full node code written, therefore creating your own altcoin as a Bitcoin clone would require you to use an implementation of the node that can perform transaction and block validation.  We have code in Haskoin for script interpreting, which is the first step towards a full node, but we have focused on getting an SPV node working instead.  There is also no support for mining in the code yet.

Of course, if you like a challenge you could do these things.  It will help you understand the intricacies of Bitcoin code, and be a lot of fun.

Cheers!

**Comment by purefn** [comment]
@xenog, thanks for the quick reply! I probably won't be able to contribute much in the short term, I still need to learn some basics. But if things go well I hope to be able to contribute in the future.

**Comment by jprupp** [comment]
We all learned Haskell while developing Haskoin.
