### ISSUE TITLE
Use sipa’s crypto library

### ISSUE THREAD

**Issue by jprupp** [jprupp/haskoin-core#162]
Use [this library](https://github.com/sipa/secp256k1).

**Comment by np** [comment]
As much as I appreciate libsecp256k1, I think that haskoin should feature a pure haskell implementation. The support for libsecp256k1 can still be added. Using a compilation flag for instance.

**Comment by np** [comment]
Given that you have already done most of the work, my suggestion would be to have a puresecp256k1 library with the exact same interface.

**Comment by jprupp** [comment]
There is a problem with cryptographic code: you should probably never attempt to write your own unless you know exactly what you are doing. Our cryptography was implemented in a very naive way. It does not run in constant time, and we have not done any analysis to make sure it will stand against common cryptographic attacks. We are not cryptographers. On top of that, the code is extremely slow.

If somebody would step in and write a cryptographic library in Haskell for secp256k1 that is both fast and resilient to common attacks, we would definitely adopt it in preference of the C secp256k1 library. So far, the only implementations of secp256k1 that I think are generally OK from a security standpoint are OpenSSL and secp256k1. I don't know if Crypto++ implements this curve, but if it did I would also trust it, although linking C++ from Haskell is probably not as straightforward as it is to link C.

For these reasons, we are pretty much stuck with secp256k1. That a cryptographic library is pure does not mean that it is necessarily better. Cryptographic code has its own issues that go well beyond referential transparency and side-effect-free computation, and Haskell's lazy evaluation may end up hurting the safety of cryptographic code more than helping. Cryptography is better done using languages that can describe what the hardware will do precisely, such as C or assembly.

Also, in x86_64 secp256k1 uses assembly code optimizations that make it run very fast.

**Comment by tphyahoo** [comment]
Isn't this done now?

**Comment by m0dev76** [comment]
Indeed, we can close this issue now.
