### ISSUE TITLE
Upgrade deepseq to >=1.4?

### ISSUE THREAD

**Issue by nuttycom** [jprupp/haskoin-core#175]
I am attempting to write an implementation of the BIP-70 Payment Protocol, and would like to take advantage of some of the Haskoin types in my implementation. In the process, I've discovered that the protobuf library (which I need for serialization of the Payment Protocol messages) relies on a more recent version of deepseq than haskoin is using. Would you accept a pull request that upgrades the deepseq version?

**Comment by jprupp** [comment]
I have upgraded this library to use LTS Haskell 3.4, which includes deepseq 1.4.1.1. I’ll close this ticket.
