### ISSUE TITLE
bip32 xkey parsing is overly complicated

### ISSUE THREAD

**Issue by tphyahoo** [jprupp/haskoin-core#191]
I am overhauling the bip32 xpubkey/xprivkey parsing and derivation machinery

This work began when I attempted to fix #192, and I noticed the current implementation is overly complex and therefore hard to fix.

I am working on simplifying the bip32 xkey handling machinery, in branch

https://github.com/tphyahoo/haskoin/commits/rework_ExtendedKeys

Hopefully I should have something ready to pull soon.

**Comment by jprupp** [comment]
It's code reading time. Thanks for this. I'll review it.

**Comment by tphyahoo** [comment]
It looks like rework_ExtendedKeys_take4 is not going to be accepted, and I understand why.

However, I still think parsing could use some love and I would like to take some of what I learned to clean up existing and make more maintainable.
