### ISSUE TITLE
number of transactions excessively high

### ISSUE THREAD

**Issue by jprupp** [jprupp/haskoin-core#195]
When syncing the testnet on perra:

```
Nov 10 22:18:58 perra hw[3905]: Reason: Received an invalid merkle block: extractMatches: number of transactions excessively high
Nov 10 22:18:58 perra hw[3905]: @(hasko_79ftBTTz0e50fQW0XBG2LI:Network.Haskoin.Node.Peer ./Network/Haskoin/Node/Peer.hs:661:15)
```

**Comment by m0dev76** [comment]
We figured this one out. We were getting 8mb block from bitcoinxtd on testnet. We increased the block size on testnet to 8mb but kept the limit at 1mb on prodnet. We need a more permanent solution however so I'll keep this bug report open until we have a permanent fix.
