### ISSUE TITLE
BIP-0044 Multi-Account Hierarchy for Deterministic Wallets

### ISSUE THREAD

**Issue by tphyahoo** [jprupp/haskoin-core#229]
I think hw is already close to following bip44, but it doesn't use the purpose field and I am not sure about the other details.

Mainly this would be a win in terms of interoperability with other wallets. Most are switching to bip44.

re-entered from historical repo at https://github.com/haskoin/haskoin-wallet/issues/127

This seems fairly straightforward. Maybe I could do it.

**Comment by jprupp** [comment]
Yeah, that is a good idea. But hold on a minute because I am working on replacing the whole account mechanism so that the wallet does not store the master key.

**Comment by tphyahoo** [comment]
Does it not store any privkeys? Or does it store privkeys, but not master key?

I'm hoping the answer is no privkeys at all are stored.  If so that's great news. Can you say more on this will work?

Will there be an assumed-online wallet, without privkeys, for generating unsigned transactions? And an assumed-offline signing wallet?  (Which I guess could be a trezor-like hardware wallet eventually)

**Comment by jprupp** [comment]
The answer is that it is optional whether to store private keys or not. There are no more keyrings, only accounts. You can test the code at https://github.com/xenog/haskoin.

That code also allows to specify an arbitrary derivation on an account, thereby supporting BIP-44, although the default derivation is set to m/0'.
