### ISSUE TITLE
Show account name for extended key in listing

### ISSUE THREAD

**Issue by tphyahoo** [jprupp/haskoin-core#233]
current listing behavior (for accounts), you get something like

```
Account: test_1_of_3
Type   : Read-Only Multisig 1 of 3
Gap    : 10
Keys   : tpubD9yc2kpcpYTFTmbE8f1N........  
tpubD9yc2kpcpYTFWC8FrcJi......
tpubD9yc2kpcpYTFXZvTjz47Z.......
```

I think it would be useful to report the internal account name associated with a pubkey, if known, so eg:

```
Account: test_1_of_3
Type   : Read-Only Multisig 1 of 3
Gap    : 10
Keys   : 
tpubD9yc2kpcpYTFTmbE8f1N........  <harry>
tpubD9yc2kpcpYTFWC8FrcJi...... <unknown>
tpubD9yc2kpcpYTFXZvTjz47Z....... <unknown>
```

the unknown accounts could then be labeled via the newread command, after which their pubkeys would show with more info.

**Comment by jprupp** [comment]
Old wallet being deprecated.
