### ISSUE TITLE
encodeTxInJs: should this report error conditions if decoding fails?

### ISSUE THREAD

**Issue by tphyahoo** [jprupp/haskoin-core#269]
```
module Network.Haskoin.Wallet.Client.Commands

.....

encodeTxInJSON :: TxIn -> Value
encodeTxInJSON (TxIn o s i) = object $
    [ "outpoint"   .= encodeOutPointJSON o
    , "sequence"   .= i
    , "raw-script" .= (cs $ encodeHex s :: Text)
    , "script"     .= encodeScriptJSON sp
    ] ++ decoded
  where
    sp = fromMaybe (Script []) $ decodeToMaybe s
    decoded = either (const []) f $ decodeInputBS s
    f inp = ["decoded-script" .= encodeScriptInputJSON inp]
```

Shouldn't sp and decoded above result in error "some message" if decoding fails?

**Comment by jprupp** [comment]
You are right, I think if there was a decoding error, it should just attempt to encode `Nothing` in JSON which will result in `null`, which is more indicative of a problem. Then the JSON field `script` should be generated with `encodeScriptJSON <$> sp` so as to use `(<$>)` from `Applicative Maybe`.

**Comment by jprupp** [comment]
Old wallet is being deprecated.
