### ISSUE TITLE
Please upload haskoin-core 0.3.0 to Hackage

### ISSUE THREAD

**Issue by runeksvendsen** [jprupp/haskoin-core#279]
Hello there, and thank you for making haskoin.

Would it be possible to have v0.3.0 of at least haskoin-core uploaded to Hackage?

And, if possible, in addition add haskoin-core to [Stackage](https://www.stackage.org/)?. If you don't want to be listed as maintainer, I'm volunteering. I've worked quite a bit with haskoin-core, and I don't mind being the contact if you'd prefer not to. I would just really like to have 0.3.0 up on Stackage, so that I can build libraries against it more easily.

**Comment by jprupp** [comment]
Good suggestion, I'll get on with it.

**Comment by runeksvendsen** [comment]
Fantastic! Thank you very much.

Good suggestion, I'll get on with it.

**Comment by runeksvendsen** [comment]
Hi there

I don't mean to rush you, but what is the status on this issue?

I would love for Hackage to be able to build my package and the documentation for it: https://hackage.haskell.org/package/bitcoin-payment-channel-0.1.1.0/reports/1

**Comment by jprupp** [comment]
Done. ;)

**Comment by runeksvendsen** [comment]
Wonderful! Thanks a lot :).
