### ISSUE TITLE
OP_PUSHDATA "" OPCODE == OP_0 should be True

### ISSUE THREAD

**Issue by runeksvendsen** [jprupp/haskoin-core#287]
`OP_PUSHDATA "" OPCODE` and `OP_0` are two different representations of the same thing: a push of an empty byte vector. In the case of `OP_PUSHDATA "" OPCODE` this is obvious (it clearly describes a push of an empty byte string), and in ine [Bitcoin wiki](https://en.bitcoin.it/wiki/Script#Constants) we can see that this is also how `OP_0` is defined.

The non-equality of these two different, but logically equivalent, representations causes an issue when first serializing a script containing `OP_PUSHDATA "" OPCODE` and then deserializing it back into the original, causing a mismatch in equality between the original object and the serialized-and-then-deserialized one.

I don't think there's a problem with having two different representations of the same thing, as long as their `Eq` instances reflect this.

Let me know if you'd like me to write the code.

**Comment by m0dev76** [comment]
Hi, thanks for reporting the bug. I can replicate it as follows:

```
λ> let s = Script [OP_PUSHDATA (pack []) OPCODE]
λ> s
Script {scriptOps = [OP_PUSHDATA "" OPCODE]}
λ> (decode $ encode s) :: Either String Script
Right (Script {scriptOps = [OP_0]})
```

We're still discussing the best way of solving it. It is a case where the `decode . encode == id` property is being violated. We'll keep you updated.

**Comment by runeksvendsen** [comment]
I should note that we will experience the same thing when we rename `OP_NOP2` to `OP_CHECKLOCKTIMEVERIFY`, as per BIP65.

I think the right way to do this would be to introduce `OP_CHECKLOCKTIMEVERIFY` alongside `OP_NOP2`, thus keeping `OP_NOP2`for backwards compatibility, but simply define that `OP_NOP2 == OP_CHECKLOCKTIMEVERIFY`, and also deserialize this opcode into `OP_CHECKLOCKTIMEVERIFY`, rather than the now deprecated `OP_NOP2`.

So, creating a Script containing `OP_NOP2`, serializing it and then deserializing it, will produce a script containing `OP_CHECKLOCKTIMEVERIFY`, but `==` will evalute to `True` for these two opcodes, so any tests should still pass.

In this transition period (before we remove `OP_NOP2` completely), we will also have a single Bitcoin opcode (OP_CHECKLOCKTIMEVERIFY) with two distinct representations (the constructors `OP_NOP2` and `OP_CHECKLOCKTIMEVERIFY`). Personally, I don't see any other solution than custom `Eq` instances, but I will await your judgement.

**Comment by jprupp** [comment]
I think you are right. If you want, create these custom `Eq` instances. I'll merge your code.

**Comment by jprupp** [comment]
Thinking about this a little more I think there is an issue between `OP_PUSHDATA ""` and `OP_0`. The issue is that the binary representations of these two different operations is not equal, therefore having two scripts containing these two instructions will yield a different hash. Although `OP_0` is the minimal representation, there are various ways to push an empty string into the stack. When comparing two scripts that contain both versions of the operation, the result should be non-equal, because the scripts, although functionally equivalent, will result in a different P2SH address, and a different transaction id for the transaction that includes it.

**Comment by ssadler** [comment]
> We're still discussing the best way of solving it. It is a case where the decode . encode == id property is being violated. We'll keep you updated.

It doesn't seem so crazy that `encode` is a lossy operation in this case, maybe the best thing to do is remove the expectation. For example, would you expect JSON or really any programming syntax to retain this property given stylistic flexibility such as whitespace and unnecessary parenthesis?

Cheeky option: remove `Binary` instance, such that `decode . encode == id` is no longer an issue!

**Comment by jprupp** [comment]
To continue commenting on this, perhaps there should be a test for truthiness for script tokens. If anyone has a strong opinion on this, and would like to submit pull request against `haskoin-core`, we can review and merge that. For now I'll consider this not to be a bug and close.
