### ISSUE TITLE
Add support for non-standard P2SH redeem scripts

### ISSUE THREAD

**Issue by hudon** [jprupp/haskoin-core#289]
I'd like Haskoin to support the building of transactions with non-standard redeem scripts in the inputs (since Bitcoin Core 0.10, rules around redeem scripts have been mostly removed and non-standard redeem scripts now get relayed correctly).

The issue is `type RedeemScript = ScriptOutput` and how `ScriptOutput` is documented as "describing standard transaction".

I feel like `type RedeemScript = Script` may make more sense, what do you think?

**Comment by hudon** [comment]
ah I think the biggest problem will be `sigKeys` which is used in `signTx` as it guesses which keys sign the input given the output we're spending. But if it's arbitrarily non-standard, we can't simply guess the key and should expect instead to be given the requirements

**Comment by hudon** [comment]
actually, adding a constructor to ScriptOutput seems much easier https://github.com/haskoin/haskoin/compare/master...hudon:hudon-arbitrary-redeem

**Comment by jprupp** [comment]
Some rewriting of things may be in order to support this. You may want to submit a patch. ;)

**Comment by hudon** [comment]
yea I tried but it changes way too many modules so I ended up writing a `signTx` for my specific case... it's probably better this way
