### ISSUE TITLE
Possible double-spend in wallet

### ISSUE THREAD

**Issue by jprupp** [jprupp/haskoin-core#298]
This double-spend has been produced by the [Testnet Faucet](http://faucet.haskoin.com/) running the Haskoin Wallet:

https://live.blockcypher.com/btc-testnet/tx/4a6e1e5fd4d93ad5730f34d9d8de14455d79322511f244d9fbe5b9ce7f3833f0/
https://live.blockcypher.com/btc-testnet/tx/4a6e1e5fd4d93ad5730f34d9d8de14455d79322511f244d9fbe5b9ce7f3833f0/

**Comment by runeksvendsen** [comment]
Looks like the two links are to the same transaction, and this transaction didn't make it into a block (I get a 404). Please share the link to the other transaction (which, presumably, made it into a block).

**Comment by jprupp** [comment]
Damn, I made a mistake. Doesn't matter. If it shows up again I'll reopen this ticket. The wallet will be rewritten anyway.
