### ISSUE TITLE
Strange memory behavior with Address' underlying ByteString

### ISSUE THREAD

**Issue by wyager** [jprupp/haskoin-core#300]
This one is a bit of a head-scratcher for me.

I'm trying to build up a big in-memory database of addresses derived from an XPubKey. Originally I was converting to a ByteString for use with a Trie, but I noticed that memory consumption was a *lot* higher than it should be. I did some more tests and it looks like each Address is using around 4kB (!!!) to store the underlying ByteString.  

Here's some test code I wrote, with a mind to ruling out other causes of memory leaks:

```hs
{-# LANGUAGE OverloadedStrings, Strict #-}
import Network.Haskoin.Crypto as Haskoin
import qualified Data.ByteString as BS
import Control.DeepSeq (NFData, force, rnf)
import Data.Hashable (hash)
import Data.Serialize (Serialize, get, put, decode, encode)
import Data.Word (Word64, Word32)


Just pubkey = Haskoin.xPubImport "xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpiaQL2jkwSB1icqYh2cfDfVxdx4df189oLKnC5fSwqPfgyP3hooxujYzAu3fDVmz"

data Compact = Compact Word64 Word64 Word32

instance Serialize Compact where
    put (Compact a b c) = put a >> put b >> put c
    get = Compact <$> get <*> get <*> get

instance NFData Compact where
    rnf (Compact a b c) = rnf a `seq` rnf b `seq` rnf c


-- Store it as some machine words
storeCompact :: Haskoin.KeyIndex -> Compact
storeCompact subkey = fromEither . decode . Haskoin.getHash160 . Haskoin.getAddrHash . Haskoin.xPubAddr $ force $  Haskoin.pubSubKey (Haskoin.pubSubKey pubkey 0) subkey
    where
    fromEither (Right x) = x

-- Around 1M used
testCompact :: IO ()
testCompact = do
    print "going"
    let bss = force $ map storeCompact [0..20000]
    print $ length bss
    print "done"

-- Store it as a bytestring
-- We even use BS.copy to make sure we're not slicing a bulky array
-- Memory behavior is the same using "encode" instead of "BS.copy . Haskoin.getHash160 . Haskoin.getAddrHash"
storeBS :: Haskoin.KeyIndex -> BS.ByteString
storeBS subkey = BS.copy . Haskoin.getHash160 . Haskoin.getAddrHash . Haskoin.xPubAddr $ force $  Haskoin.pubSubKey (Haskoin.pubSubKey pubkey 0) subkey

-- Around 80M used. Why? 2e4*(20 + 16) isn't even close to 80M.
testBS :: IO ()
testBS = do
    print "going"
    let bss = force $ map storeBS [0..20000]
    print $ length bss
    if all ((== 20) . BS.length) bss
        then print "Length correct"
        else print "Length wrong"
    print "done"

main = testCompact
```

Looking at the output of `+RTS -hc`, all of this overhead is `PINNED`, so it is coming from the ByteStrings.

I doubt this is a problem with Haskoin-core itself; even if, for some reason, it was generating really inefficiently sliced bytestrings, the `BS.copy` should fix that. I'm just not really sure where to look next. The fact that it's ~4k per bytestring (each of which is only 20 bytes long) makes me think it might be some sort of allocation issue where the bytestrings are only being allocated on page boundaries, but that's pure speculation. Maybe something playing poorly with the Secp256k1 FFI calls?

Any suggestions? Am I overlooking something obvious?

**Comment by jprupp** [comment]
I am not sure what the problem may be here, but it seems to be about optimising performance, and not a real problem in the code. Unfortunately I am not so familiar with low-level GHC stuff. Feel free to ask around those circles. They may be able to give you the insights you are looking for. I will close this ticket for now, but feel free to respond to it if you find what may be going on.
