### ISSUE TITLE
Bech32 & segwit address support

### ISSUE THREAD

**Issue by afk11** [jprupp/haskoin-core#319]
I've been reviewing for common libraries that may not yet have segwit address support. I haven't seen anyone work on it here yet, please add this soon!

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by jprupp** [comment]
Hey @afk11!

I did it in bitcoinJ already! I'll do it here eventually.

Cheers!

**Comment by ysangkok** [comment]
ping @xenog , are you still planning on this?

**Comment by jprupp** [comment]
Eventually, unless somebody sends a pull request.

**Comment by jprupp** [comment]
Work is in progress. Some of the SegWit support already landed.
