### ISSUE TITLE
Old (?) repo give bad impression

### ISSUE THREAD

**Issue by cies** [jprupp/haskoin-core#339]
I looked at this:

https://github.com/MichaelBurge/haskoin

And luckily thought, "Haskoin is quite an alive project, how come so quiet here?" Then found this repo.

I think the old repo should be referring peeps here (in the README and/or the GH project description).

**Comment by runeksvendsen** [comment]
Hi there

The repo you mention is not an old Haskoin repo, but rather a repo created recently, related to the following blog post about a generic blockchain data structure: http://www.michaelburge.us/2017/08/17/rolling-your-own-blockchain.html

If you’re confused about two different projects both using the “Haskoin” name, I think it would make sense to notify @MichaelBurge, to let him know the choice of name for his project clashes with an existing one.

**Comment by cies** [comment]
Sorry I was unaware of this. I'll give him a heads-up.
