### ISSUE TITLE
Windows build compatibility?

### ISSUE THREAD

**Issue by ubamnow404** [jprupp/haskoin-core#346]
I try to use haskoin on windows with ghc 8.0.2. secp256k1 asks for automake, and fails when it's missing:

```
./autogen.sh: line 3: autoreconf: command not found
```

Automake not available for windows, maybe with cygwin? But I hope to stay with regular cmd.exe for now.

Do anyone build haskoin on windows? If yes, how?

**Comment by jprupp** [comment]
As nobody answered, I will close this. If somebody does testing in Windows and manages to make it work, I'll accept any pull requests on the next version.
