### ISSUE TITLE
Remove dependency on deprecated cryptohash library. 

### ISSUE THREAD

**Issue by ovangle** [jprupp/haskoin-core#351]
Hey, first of all thanks for the great work on the library, although I'm currently working from a local package install to get it working with 8.4.1... I had to widen constraints on `either` and `entropy` libraries in order to not get dependency conflicts with `base`. 

Y'anyway... would it be possible to replace the SHA* and RIPEMD hashes with ones from cryptonite?

**Comment by jprupp** [comment]
Yes, this is being done at the moment on my personal development branch as well as @plaprade's. It will be merged once it is ready and sufficiently tested.
