### ISSUE TITLE
FromJSON instances

### ISSUE THREAD

**Issue by wraithm** [jprupp/haskoin-core#361]
I think you did some wonderful work getting rid of the `IORef` for network! I really love this new format. However, I do think that we can get `FromJSON` instances in haskoin that aren't too bad.

I'll use `Address` as an example, but these proposals should all work for all the other types that depend on network. Here are the three options that I see that make sense:

## 1
Newtypes for network dependent instances, something like this:
```haskell
newtype BTCAddress = BTCAddress { getBTCAddress :: Address }
    deriving (Show, Eq, Read, Ord, NFData, ToJSON)

instance FromJSON BTCAddress where
    parseJSON = fmap BTCAddress . addrFromJSON btc
```

I think this is the simplest low-fuss solution. It's just a little verbose.

## 2
Mirror your `Read` instances in `FromJSON` and just try all networks until it works. This may cause confusing behavior for people who are trying to use this library to use bitcoin cash. However, at least this is symmetric with `Read` and gets the right behavior for people using normal bitcoin. We could combine this with idea 1 to give people bitcoin cash support. As in, if you're using normal bitcoin, use `Address`, if you're using bitcoin cash base58, use `BCHAddress` which would be a newtype around `Address`.

I think this bitcoin cash issue kind of indicates that maybe we should be doing something different for bitcoin cash support entirely. Maybe compile time flags? GADTs? Backpack? Template haskell? My third option (see below)? Maybe even bitcoin cash should even be in a separate library with newtype wrappers or something. Just throwing out random vague ideas here... I don't have any amazing suggestions, but this feels off overloading the bitcoin and bitcoin cash types.

Anyways, here's the idea:
```haskell
tryAllNets :: (Network -> a -> Maybe b) -> a -> Maybe b
tryAllNets f x = foldl' tryNet Nothing allNets
  where tryNet k n = k <|> f n x

instance FromJSON Address where
    parseJSON = withText "address" $
        maybe (fail "could not decode address") return . tryAllNets stringToAddr
```

## 3
This is more speculative and a big departure from how things work now. The idea is having all of the network determined types take a phantom type variable that gives you the ability to pull up the correct network. This makes it so you'll have to specify the network if it's ambiguous, but we already have to do that anyways. The `TypeApplications` GHC extension works well though in those cases. One of the benefits of this though is that bitcoin cash support is quite natural and safe.

```haskell
data Address net = ...

data BTC
data Testnet

class Network net where
   network :: Proxy net -> Network

instance Network BTC where network = btc
instance Network Testnet where network = btcTest

instance Network net => FromJSON (Address net) where
  parseJSON = addrFromJSON (network (Proxy :: Proxy net))
```

@xenog Tell me what you think. I'd be happy to implement whatever solution you think is best.

**Comment by jprupp** [comment]
Hello Mathew,

I think the phantom type solution is probably the most interesting of the bunch. I tried some of what you are proposing, specifically having `allNets` being used to discover the right network for an address. The main problem is with Base58 addresses. The address does not encode whether it belongs to the `btcreg` or `btctest` network, so when decoding Base58 I have to consider the test addresses to be from the `btctest` network by default. For CashAddr and Bech32 it is easy: all networks have different prefixes.

A drawback of making the network get detected automatically from an address is that you may not be intending to do this. You may be running a program that should only accept CashAddr and fail early if you pass anything else. I would not want to have the programmer test for a network, but rather force to pass the network explicitly before parsing. This would also work if the network is part of the type.

Greetings

**Comment by jprupp** [comment]
Hello Matthew,

I'm having a coffee and remembered why the network cannot be part of the type: you must compile an executable or a library for a specific network only, and cannot make it work with all. That is utterly inconvenient. My previous suggestion to work on solution 3 will not be practical.

Cheers

**Comment by wraithm** [comment]
Hey @xenog,

You can do dynamic network executables, it's just all of the options are a little awkward. You either have to do some pain with existential types (kind of like `SomeException` in `base`, you'd have "`SomeAddress`"), or you need an enumeration of the network options, or you pass around `Proxy`s everywhere, like this:

```haskell
data Network = Mainnet | Testnet | Regtest deriving (Show, Eq, Ord)


decodeAddr :: NetworkType net => Proxy net -> ByteString -> Maybe (Address net)
decodeAddr _ = decodeStrict


printAddr :: NetworkType net => Proxy net -> ByteString -> IO ()
printAddr p bs = print $ decodeAddr p bs


main :: IO ()
main = do
    net <- parseArgs
    case net of
        Mainnet -> printAddr (Proxy :: Proxy Mainnet) testAddr
        Testnet -> printAddr (Proxy :: Proxy Testnet) testAddr
        Regtest -> printAddr (Proxy :: Proxy Regtest) testAddr
```

There are options to make the third case work, but I very much so agree that they're all quite awkward.

I have some other thoughts that I want to flesh out before writing them down here, but I've got some ideas for some rearranging of the types that makes it work. Some of it involves separating bitcoin cash support into a newtype. What do you think about that? Like, `Address` is either Bitcoin Base58/Bech32 on Bitcoin Mainnet, Testnet, or Regtest, then `BCHAddress` (or `Address` just moved to the bitcoin cash module) is either Base58/CashAddr on the bitcoin cash networks. I think that my new thought would actually be more correct because then you can't confuse the addresses. Are you open to the idea of having Bitcoin and Bitcoin Cash be separate types? I think I can solve the Testnet Regtest distinction that you mentioned in your first comment if we make that assumption!

**Comment by jprupp** [comment]
Hey Matthew,

The networks are almost completely overlapping, and if things are split into different types, lots of network-agnostic code will no longer be possible. For example the Haskoin Store has a command-line argument for choosing on which network it is to operate. The ability to choose a different network at runtime, and even work with various networks in the same executable in an agnostic manner is desirable. That ability is used extensively in the test suite.

A possible solution to go about this is to make the network implicit by creating a `ReaderT Network m a`, but that still doesn't solve provide the ability to have `FromJSON` instances for addresses and extended keys that work across all supported networks.

It is possible to have addresses and keys flagged with a phantom type as unsafe, such that you must pass them through a filter function that can turn it into an address or key in the network that you intend to use if it is safe to do so:

```haskell
data DirtyAddress
data CleanAddress
data Address flag = PayToPubKeyHash Hash256 Network
instance FromJson (Address DirtyAddress)
cleanAddress :: Network -> Address DirtyAddress -> Maybe (Address CleanAddress)
```

Cheers

**Comment by jprupp** [comment]
I will close this issue for now, as it is not something that will be fixed. Feel free to follow up with a pull request, or reopen if needed.
