### ISSUE TITLE
Add Script Validation Engine

### ISSUE THREAD

**Issue by ProofOfKeags** [jprupp/haskoin-core#372]
One of the main barriers to getting this to be a full node implementation would be full transaction validation. The main thing missing from this is a Script Validation engine. I am opening this issue with the intention of taking this work on.

Currently I have not committed to implementing it, much less by any particular deadline, but I intend to at least scope the work before making further decisions about actually implementing it. Any discussion on this topic is welcome on this thread.

**Comment by jprupp** [comment]
I don't think we should consider this a priority at the moment. I'm going to close and let work happen in a fork/branch until it is ready for merging.
