### ISSUE TITLE
`bech32Encode` generates invalid output if the HRP contains upper case characters.

### ISSUE THREAD

**Issue by jonathanknowles** [jprupp/haskoin-core#375]
## Overview

When [`bech32Encode`](https://github.com/haskoin/haskoin-core/blob/d14b988dcfd96e20ec260ff8fd2f45f288c8587f/src/Network/Haskoin/Address/Bech32.hs#L131) is called with a human-readable part that contains one or more **upper-case characters**, it produces in an **invalid** Bech32 string that cannot be decoded with the `bech32Decode` function.

## Analysis

As part of the encoding process, the human-readable part is converted to lower case:

https://github.com/haskoin/haskoin-core/blob/d14b988dcfd96e20ec260ff8fd2f45f288c8587f/src/Network/Haskoin/Address/Bech32.hs#L136

However, the checksum is calculated **before** the conversion to lower case takes place:

https://github.com/haskoin/haskoin-core/blob/d14b988dcfd96e20ec260ff8fd2f45f288c8587f/src/Network/Haskoin/Address/Bech32.hs#L134

This contradicts the [Bech32 specification](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32), which states:

> "The lowercase form is used when determining a character's value for checksum purposes."

Therefore, if the original human-readable part contains one or more upper case characters:

1. the generated checksum will be inconsistent with the human-readable prefix of the output string
2. the output string will fail to decode.

## Example

Consider the following two calls to `bech32Encode`, differing only in the case of the human-readable part:
```hs
> bech32Encode "test" []
> bech32Encode "TEST" []
```
### Expected Behaviour

Both calls to `bech32Encode` should result in the **same** output string:
```hs
> bech32Encode "test" []
Just "test12hrzfj"
> bech32Encode "TEST" []
Just "test12hrzfj"
> bech32Encode "test" [] == bech32Encode "TEST" [] 
True
```

### Actual Behaviour

The above calls to `bech32Encode` **actually** result in **different** output strings:
```hs
> bech32Encode "test" []
Just "test12hrzfj"
> bech32Encode "TEST" []
Just "test13jgcyw"
> bech32Encode "test" [] == bech32Encode "TEST" [] 
False
```
Attempting to decode the string produced by `bech32Encode "TEST" []` results in `Nothing`:
```hs
> bech32Decode "test13jgcyw"
Nothing
```

**Comment by jonathanknowles** [comment]
This bug is also present in the [Haskell reference implementation for Bech32](https://github.com/sipa/bech32/issues/49), for which a [fix](https://github.com/sipa/bech32/pull/50) is available.

**Comment by jprupp** [comment]
Thank you for this report. I'll fix it for the next release.
