### ISSUE TITLE
ED25519 Support?

### ISSUE THREAD

**Issue by JuliaBonita** [jprupp/haskoin-core#377]
Thank you for creating this repo. It has helped me to learn a lot about Haskell-based crypto.

Given that ED25519 has some significant security and performance advantages and much of the crypto community is moving to ED25519, do you plan to add ED25519 support to Haskoin (including support for multisig) at some point?

**Comment by jprupp** [comment]
If Bitcoin Cash adds ED25519 signatures to transactions then I would add support in Haskoin for that. I am not at the moment aware of efforts in that direction. Bitcoin signatures use the SECP256K1 curve exclusively at the moment.

**Comment by JuliaBonita** [comment]
Thank you for your reply. The Bitcoin Core team is adding Schnorr signatures to [their secp256k1 implementation](https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki) very soon. You probably already know that ED25519 and Schnorr signatures are essentially the same thing, but they just use different EC curves. That means Bitcoin will get the benefits of ED25519 while still preserving the security guarantees of secp256k1. So this is really exciting.

Andrew Poelstra has confirmed this in many places, too. They've already written the code and it's in testing now.

Is that BIP proposal enough for you to work with or do you still need to wait until they push the code into the Bitcoin Core repo?

**Comment by JuliaBonita** [comment]
I just noticed that Bitcoin Cash has already [started adding Schnorr signatures, too](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2019-05-15-upgrade.md).

**Comment by jprupp** [comment]
I haven't considered this a priority for this package, but I would merge a patch if it lands on my lap.
