### ISSUE TITLE
SegWit transaction support

### ISSUE THREAD

**Issue by diogob** [jprupp/haskoin-core#379]
Dear maintainers,

First thanks for open sourcing this great work. I've been using haskoin-store for a while and it's a really nifty tool.
Second, from what I could observer the function `signTx` cannot produce a SegWit transaction, is that correct? I say this because of the implementation of [sigKeys](https://github.com/haskoin/haskoin-core/blob/master/src/Network/Haskoin/Transaction/Builder.hs#L352)

I have decoded some SegWit transactions using the JSON decoders and saw the `txWitness` field of my `Tx` be populated. So I was wondering if I could use the `makeSignature` to sign a SegWit transaction and just add the binary string to the `txWitness` field. 

Also, I would be willing to put some hours towards a PR to implement this if you folks could give me some pointers.

**Comment by jprupp** [comment]
Knock yourself out mate. I didn't add support for SegWit transactions to transaction signing code. Make sure to write tests for your code if you do.

**Comment by GambolingPangolin** [comment]
I'm currently working on improving the segwit (and taproot) support.  This is good motivation to finish the segwit portion up sooner rather than later.
