### ISSUE TITLE
hackage documentation missing again

### ISSUE THREAD

**Issue by fatmalama** [jprupp/haskoin-core#390]
the latest version on hackage lacks documentation. apparently a bug way back in 2017 #277, I don't know what has happened ever since because I've just discovered haskoin

**Comment by GambolingPangolin** [comment]
The [docs hosted on stackage][1] usually build correctly, although you will not always find completely up-to-date docs.  The current version there includes a big recent namespace organization and should be adequate to get familiar with the library.

[1]: https://www.stackage.org/package/haskoin-core

**Comment by jprupp** [comment]
Yeah, go for Stackage documentation. I stopped caring about updating Hackage since Stackage exists.
