### ISSUE TITLE
Network, undocumented

### ISSUE THREAD

**Issue by fatmalama** [jprupp/haskoin-core#391]
I don't understand what network is for from reading the source or why I need it for importing a xpub string, nor how to provide it

**Comment by fatmalama** [comment]
ok I get it now, you select a blockchain network. maybe it could be said on the Network data definition instead of "Constants for network"

**Comment by jprupp** [comment]
If you have any clarification suggestions to improve documentation please send pull request. I'm closing this issue but sometime in the future I will take a good at all the project's documentation.
