### ISSUE TITLE
Deprecate support for BCH

### ISSUE THREAD

**Issue by ProofOfKeags** [jprupp/haskoin-core#410]
The fact that BTC and BCH have a common history don't have a bearing on their future developments. Feature sets have diverged over the last several years. Best to fork the codebase in two rather than keeping both sets of functionality in a single library.

**Comment by jprupp** [comment]
I don't expect Bitcoin Core and Bitcoin Cash to stray far enough from each other such that it becomes easier to support both networks with two separate codebases.

If it becomes harder to support Bitcoin Core and Bitcoin Cash than it is now, my approach will be to perform major changes, probably in a non-backwards-compatible manner, to separate more cleanly the network-dependent code.
