### ISSUE TITLE
Support for stealth payments

### ISSUE THREAD

**Issue by np** [jprupp/haskoin-core#85]
If their is interest for this feature in Haskoin, I could get around working on a patch.
Resources on stealth payments [here](https://wiki.unsystem.net/en/index.php/DarkWallet/Stealth)

**Comment by m0dev76** [comment]
I like the idea behind stealth payments and we would definitively add them to haskoin if you want to work on them. We are also looking to support bip70 payment protocol eventually.

**Comment by jprupp** [comment]
Would this be something that would go here or in haskoin-wallet?

**Comment by m0dev76** [comment]
The cryptography primitives would go here in haskoin and the wallet part would go into haskoin-wallet. Much like extended keys.

**Comment by np** [comment]
Exactly, I would say that all the pure code can go to haskoin. In haskoin-wallet can go what is specific to the persistent storage and the wallet interface itself.

I'm still slightly concerned by the lack of standardization around stealth addresses. Also some changes are from November (https://wiki.unsystem.net/en/index.php/DarkWallet/Stealth)
